<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Mesin_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get mesin by ID
     */
    function get_mesin($ID)
    {
        return $this->db->get_where('mesin',array('ID'=>$ID))->row_array();
    }
        
    /*
     * Get all mesin
     */
    function get_all_mesin()
    {
         $this->db->order_by('ID');
            return $this->db->get('mesin')->result_array();
    }
        
    /*
     * function to add new mesin
     */
    function add_mesin($params)
    {
        $this->db->insert('mesin',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update mesin
     */
    function update_mesin($ID,$params)
    {
        $this->db->where('ID',$ID);
        return $this->db->update('mesin',$params);
    }
    
    /*
     * function to delete mesin
     */
    function delete_mesin($ID)
    {
        return $this->db->delete('mesin',array('ID'=>$ID));
    }
}
